{% set name = "junifer-data" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/junifer_data-{{ version }}.tar.gz
  sha256: 5957731367477b6c3f8905c7400432914a3d018e318acfc23a6e0492c55529ac

build:
  entry_points:
    - junifer-data = junifer_data._cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=70
    - setuptools-scm >=8
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.1.3,<8.2
    - datalad >=1.0.0,<1.2.0
    - lazy_loader ==0.4

test:
  imports:
    - junifer_data
  commands:
    - pip check
    - junifer-data --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/juaml/junifer-data-client
  summary: Python client for junifer-data
  license: AGPL-3.0-only
  license_file: LICENSE
  dev_url: https://github.com/juaml/junifer-data-client

extra:
  recipe-maintainers:
    - synchon
